<?php
$homeUrl = $this->url('home',array(),array('force_canonical' => true));
?>
<section class="invoice">
          <!-- title row -->
          <div class="row">
            <div class="col-xs-12">
              <h2 class="page-header">
                 SO#<?php echo $salesorderData['_id'];?> - <?php echo $salesorderData['customer']?>
                <small class="pull-right" style="padding-left:5em"><?php echo Date('m/d/Y', $salesorderData['created']->sec);?></small>
              </h2>
            </div><!-- /.col -->
          </div>
          <!-- info row -->

          <div class="row invoice-info">
 <!--            <div class="col-sm-4 invoice-col">
              From
              <address>
                 C3K Philippines, Inc.</strong><br>
                Email: contact@zaka.ph
              </address>
            </div><!-- /.col --> 
            <div class="col-sm-4 invoice-col">
              Customer:
              <br/>
              <address>
                <strong>Name:</strong> <?php echo $salesorderData['customer']?><br>
                <strong>Phone:</strong> <?php echo $salesorderData['phone']?><br>
                <strong>Address:</strong> <?php echo $salesorderData['deliveryAddr']?><br>
              </address>
            </div><!-- /.col -->

            
            <div class="col-sm-4 invoice-col">
              Payment:
              <br/>
              <b>Payment via:</b> <?php echo $salesorderData['paymentType']?><br>
              <b>Paid:</b> <?php echo ($salesorderData['paid'] === TRUE)? Date('M d Y ', $salesorderData['paid_date']->sec) : 'Unpaid' ?> <br>
              <b>Seller:</b> <?php echo $salesorderData['seller'];?> <br>
            </div><!-- /.col -->

            <div class="col-sm-4 invoice-col">
              Delivery:
              <br/>
              <b>Type:</b> <?php echo $salesorderData['deliveryType']?><br>
                <strong>Date:</strong> <?php echo $salesorderData['shipmentDate']?> - 
                        <?php echo $salesorderData['deliveryTime']?>
                      <br>
              <b>Delivered:</b> <?php echo ($salesorderData['shipped'] === TRUE)? Date('M d Y ', $salesorderData['shipped_date']->sec) : 'Not yet' ?> <br>
              <b>Rider:</b> <?php echo $salesorderData['rider']; ?> <br>
            </div><!-- /.col -->

          </div><!-- /.row -->

          <!-- Table row -->
          <div class="row">
            <div class="col-xs-12 table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Qty</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Subtotal</th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach($salesorderData['items'] as $item){?>
                  <tr>
                    <td><?php echo $item['qty']?></td>
                    <td><?php echo $item['sku']?></td>
                    <td><?php echo number_format($item['price'],2)?></td>
                    <td><?php echo number_format($item['discount'],2)?></td>
                    <td><?php echo number_format($item['subtotal'],2)?></td>
                  </tr>
                <?php }?>
                </tbody>
              </table>
            </div><!-- /.col -->
          </div><!-- /.row -->

          <div class="row">
            <!-- accepted payments column -->
            <div class="col-xs-6">
              Notes:
                <pre class="text-muted well well-sm no-shadow" style="font-style:italic; font-size:.9em; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;" ><?php echo $salesorderData['note'];?></pre>  
            </div><!-- /.col -->
            <div class="col-xs-6">
              <!-- <p class="lead">Amount Due 2/22/2014</p> -->
              <div class="table-responsive">
                <table class="table">
                  <tbody><tr>
                    <th style="width:50%">Subtotal:</th>
                    <td><?php echo number_format($salesorderData['total'],2)?></td>
                  </tr>
<!--                   <tr>
                    <th>Shipping:</th>
                    <td>$5.80</td>
                  </tr> -->
                  <tr>
                    <th>Total:</th>
                    <td>&#8369; <?php echo number_format($salesorderData['total'],2)?></td>
                  </tr>
                </tbody></table>
              </div>
            </div><!-- /.col -->
          </div><!-- /.row -->
          <div class="row">
            <div class="col-sm-12">
              <span class=" pull-right">
              C3K Philippines, Inc. - contact@zaka.ph
              </span>
            </div>
          </div>
          <!-- this row will not appear when printing -->
          <div class="row no-print">
            <div class="col-xs-12">
              <a href="?print=true" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>
              
              <?php if ($salesorderData['shipped'] !== TRUE) {?>
                <a href="<?php echo $homeUrl;?>salesorder/markasdelivered/<?php echo $salesorderData['_id']?>">
                   <button class="btn btn-primary pull-right" style="margin-left: 5px;">
                   <i class="fa fa-truck"></i>
                    Mark as Delivered</button>
                </a>  
              <?php } ?>


              <?php if ($salesorderData['paid'] == FALSE) {?>
              <a href="#paymentmodal" data-toggle="modal">
              <!-- <a href="<?php echo $homeUrl;?>salesorder/markaspaid/<?php echo $salesorderData['_id']?>"> -->
                 <button class="btn btn-success pull-right" style="margin-left: 5px;">
                 <i class="fa fa-credit-card"></i>
                  Create Payment</button>
              </a>
              <?php }?>

            </div>

            <div class="modal fade" id="paymentmodal">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Create Payment</h4>
                  </div>
                  <div class="modal-body">
                    <p>One fine body…</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

          </div>
        </section>
        <script src="<?php echo $homeUrl;?>js/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>

        <script type="text/javascript">

   

        </script>