<div class="box">
    <div class="box-header">
        <h3 class="box-title">Products</h3>
        <div class="box-tools">
            <div class="input-group">
                <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search">
                <div class="input-group-btn">
                    <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </div>
    </div><!-- /.box-header -->
    <div class="box-body table-responsive no-padding">
        <table class="table table-hover table-bordered">
            <tbody><tr>
                <th>Sku</th>
                <th>Item Name</th>
                <th>Capital Price</th>
                <th>Price</th>
                <th>Stock Count</th>
                <th>Actions </th>
            </tr>
            <?php foreach($data as $product){ ?>
            <tr>
                <td><?php echo $product['sku'];?></td>
                <td><?php echo $product['itemname'];?></td>
                <td style="text-align:right"><?php echo number_format($product['coreprice'],2);?></td>
                <td style="text-align:right"><?php echo number_format($product['price'], 2);?></td>
                <td><?php echo $product['stock'];?></td>
                <td>
                    <a href="<?php echo $this->basePath();?>/product/update?product_id=<?php echo $product['_id']?>">
                    <button class="btn btn-primary btn-sm">
                         Edit 
                    </button>
                    </a>
                    <a href="#" style="padding-left:20px"> Delete </a>
                </td>
            </tr>
           <?php } ?>
        </tbody></table>
    </div><!-- /.box-body -->
</div>