<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Backend\Module'                       => __DIR__ . '/Module.php',
  'Backend\Controller\ProductController' => __DIR__ . '/src/Backend/Controller/ProductController.php',
  'Backend\Controller\OrderController'   => __DIR__ . '/src/Backend/Controller/OrderController.php',
  'Backend\Controller\SalesOrderController'   => __DIR__ . '/src/Backend/Controller/SalesOrderController.php',
  'Backend\Controller\UserController'    => __DIR__ . '/src/Backend/Controller/UserController.php',
  'Backend\Model\Orders'                 => __DIR__ . '/src/Backend/Model/Orders.php',
  'Backend\Model\SalesOrders'                 => __DIR__ . '/src/Backend/Model/SalesOrders.php',
  'Backend\Model\Sequence'                 => __DIR__ . '/src/Backend/Model/Sequence.php',
  // 'Backend\Model\Users  '                 => __DIR__ . '/src/Backend/Model/UserController.php',
  'Backend\Model\ProductVariants'        => __DIR__ . '/src/Backend/Model/ProductVariants.php',
  'Backend\Model\Products'               => __DIR__ . '/src/Backend/Model/Products.php',
);
