<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Backend\Module'                       => __DIR__ . '/Module.php',
  'Backend\Controller\ProductController' => __DIR__ . '/src/Backend/Controller/ProductController.php',
  'Backend\Model\ProductVariants'        => __DIR__ . '/src/Backend/Model/ProductVariants.php',
  'Backend\Model\Products'               => __DIR__ . '/src/Backend/Model/Products.php',
);
