<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Backend\Module'                     => __DIR__ . '/Module.php',
  'Backend\Controller\IndexController' => __DIR__ . '/src/Backend/Controller/IndexController.php',
  'Backend\Model\Products'             => __DIR__ . '/src/Backend/Model/Products.php',
);
